[build]
  command = "npm run build"
  publish = "dist/client"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "dist"

[[plugins]]
  package = "@netlify/plugin-sitemap"
